version: "3"
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    image: ${DRUPAL_IMAGE_NAME}
    container_name: ${DRUPAL_CONTAINER_NAME}
    ports:
      - ${DRUPAL_PORT}:80
    volumes:
      - ./app:/app
      - ./install:/install
    restart: always
volumes:
  db_data: